nome = input('digite seu nome?')
idade = input ("qual sua idade?")
peso = input ('qual seu peso?')
print ('então você se chama?')
print (nome)
print ('e você tem')
print( idade )
print ('anos')
print ('e pesa')
print (peso)
